create database FinalProjectWeb
go 

use FinalProjectWeb
go

--Tạo bảng User
CREATE TABLE [Users] (
    UserID BIGINT IDENTITY (1,1) NOT NULL,
    UserName NVARCHAR(50) NULL DEFAULT NULL,
    NumPhone CHAR(12) UNIQUE NULL,
    Email CHAR(50) UNIQUE NULL,
    [Password] CHAR(24) NOT NULL,
    Avatar CHAR(100) NULL DEFAULT NULL,
    CONSTRAINT PK_Users PRIMARY KEY (UserID)
);
go


-- Bản Post
CREATE TABLE Post
(
    PostID BIGINT IDENTITY(1,1) NOT NULL,
    UserID BIGINT NOT NULL,
    Content NVARCHAR(2048) NULL DEFAULT NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NULL DEFAULT NULL,
    CONSTRAINT PK_Post PRIMARY KEY NONCLUSTERED (PostID), -- Thêm khóa chính
    INDEX IX_Post_UserID NONCLUSTERED ([UserID]), -- Thêm chỉ mục cho UserID
    CONSTRAINT FK_Post_User FOREIGN KEY ([UserID]) REFERENCES [Users]([UserId]) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go

--Bảng Comment
CREATE TABLE Comment(
  CommentID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  UserID BIGINT NOT NULL,
  PostID BIGINT NOT NULL,
  Content NVARCHAR(2048) NULL DEFAULT NULL,
  CreatedAt DATETIME2 NOT NULL,
  UpdatedAt DATETIME2 NULL DEFAULT NULL,
  FOREIGN KEY (UserID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (PostID) REFERENCES [Post](PostID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go

--Bảng Like
CREATE TABLE [Like](
  LikeID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  UserId BIGINT NOT NULL,
  PostID BIGINT NOT NULL,
  CreatedAt DATETIME2 NOT NULL,
  UpdatedAt DATETIME2 NULL DEFAULT NULL,
  FOREIGN KEY ([UserID]) REFERENCES [Users]([UserID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (PostID) REFERENCES [Post](PostID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go


--Bảng Message
CREATE TABLE [Message] (
  MessID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  SenderID BIGINT NOT NULL,
  ReceiverID BIGINT NOT NULL,
  Content NVARCHAR(2048) NULL DEFAULT NULL,
  CreatedAt DATETIME2 NOT NULL,
  UpdatedAt DATETIME2 NULL DEFAULT NULL,
  FOREIGN KEY (SenderID) REFERENCES [Users]([UserID]) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (ReceiverID) REFERENCES [Users]([UserID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go

-- Bảng Messfolder
CREATE TABLE Messfolder (
  MessFoID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  MessID BIGINT NOT NULL,
  MessFoImageLink NVARCHAR(2048) NULL DEFAULT NULL,
  FOREIGN KEY (MessID) REFERENCES [Message](MessID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go

--Bảng Conversation
CREATE TABLE [Conversation] (
  ConverID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  CallerID BIGINT NOT NULL,
  ReceiverID BIGINT NOT NULL,
  Created_at DATETIME2 NOT NULL DEFAULT GETDATE(),
  Updated_at DATETIME2 NOT NULL DEFAULT GETDATE(),
  deleted_at DATETIME2 NULL,
  FOREIGN KEY (CallerID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (ReceiverID) REFERENCES [Users](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go

--Bảng Participants
CREATE TABLE Participants (
  ParID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  ConverID BIGINT NOT NULL,
  UserID BIGINT NOT NULL
  FOREIGN KEY (ConverID) REFERENCES [Conversation](ConverID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
go

CREATE UNIQUE INDEX participants_UNIQUE ON Participants (
  ConverID,
  UserID
);
go
